api/urls.py
from .views import *
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

router = DefaultRouter()
router.register(r'publishers', PublisherViewSet, basename='publishers-api')
router.register(r'contributors', ContributorViewSet, basename='contributors-api')
router.register(r'books', BookViewSet, basename='books-api')
router.register(r'reviews', ReviewViewSet, basename='reviews-api'),
router.register(r'users', UserViewSet, basename='users-api')
 
urlpatterns = [
  path("login/", CustomTokenObtainPairView.as_view(), name="login"),
  path("refresh/", TokenRefreshView.as_view(), name="refresh"),
  path("auth/", include("rest_framework.urls")),
] + router.urls

bookr/urls.py
from django.contrib import admin, auth
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',  admin.site.urls),
    path('', include('reviews.urls')),
    path('api-real/', include('api.urls')),
    path("accounts/",include(("django.contrib.auth.urls", "auth"), namespace="accounts")),
    path("accounts/password_reset/done/", auth.views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("accounts/reset/done/", auth.views.PasswordResetCompleteView.as_view(), name="password_reset_complete",),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
from django.db import models
from django.contrib import auth
from django.utils.text import slugify


# Create your models here.
class Publisher(models.Model):
  name = models.CharField(max_length=50, help_text="The name of the Publisher")
  website = models.URLField(help_text="The Publisher's website")
  email = models.EmailField(help_text="The Publisher's email address")
  
  def __str__(self):
    return self.name


class Contributor(models.Model):
  first_names = models.CharField(max_length=50, help_text="The contributor's first name or names.")
  last_names = models.CharField(max_length=50, help_text="The contributor's last name or names.")
  email = models.EmailField(help_text="The contact email for the contributor.")
  
  def __str__(self):
    return f"{self.first_names} {self.last_names}"
  
  
class Book(models.Model):
  title = models.CharField(max_length=70, help_text="The title of the book")
  slug = models.SlugField(max_length=70, null=True, blank=True)
  cover = models.ImageField(upload_to='book_covers/', blank=True, null=True)
  sample = models.FileField(upload_to='book_samples/', blank=True, null=True)
  publication_date = models.DateField(verbose_name="Date the book was published.")
  isbn = models.CharField(max_length=20, verbose_name="ISBN number of the book.")
  publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
  contributor = models.ManyToManyField(Contributor, through="BookContributor")
  
  def __str__(self):
    return f"{self.title} ({self.isbn})"
  
  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = slugify(self.title)
    super(Book, self).save(*args, **kwargs)

  
class BookContributor(models.Model):
  class ContributionRole(models.TextChoices):
    AUTHOR = "AUTHOR", "Author"
    CO_AUTHOR = "CO-AUTHOR", "Co-Author"
    EDITOR = "EDITOR", "Editor"
  book = models.ForeignKey(Book, on_delete=models.CASCADE)
  contributor = models.ForeignKey(Contributor, on_delete=models.CASCADE)
  role = models.CharField(verbose_name="The role this contributor had in the book.", choices=ContributionRole.choices, max_length=20)
  
  
class Review(models.Model):
  content = models.TextField(help_text="The Review text.")
  rating = models.IntegerField(help_text="The rating the reviewer has given.")
  date_created = models.DateTimeField(auto_now_add=True, help_text="The date and time the review was created.")
  date_edited = models.DateTimeField(null=True, help_text="The date and time the review was last edited.")
  creator = models.ForeignKey(auth.get_user_model(), on_delete=models.CASCADE)
  book = models.ForeignKey(Book, on_delete=models.CASCADE, help_text="The Book that this review is for.")

templates/pages/book-detail.html
{% extends '../layouts/base.html' %}

{% block body %}
<h2 class="mt-3">Book Details</h2>
<hr>
{% if book.cover %}
<img src="{{ book.cover.url }}" alt="Book Thumbnail">
<br>
{% endif %}
{% if book.sample %}
<span class="text-info">Sample: </span>
<span><a href="{{ book.sample.url }}">Download</a></span>
<br>
{% endif %}
<span class="text-info">Title: </span>
<span>{{ book.title }}</span>
<br>
<span class="text-info">Publisher: </span>
<span>{{ book.publisher }}</span>
<br>
<span class="text-info">Publication Date: </span>
<span>{{ book.publication_date }}</span>
<br>
{% if book.avg_rating %}
<span class="text-info">Overall Rating: </span>
<span class="badge badge-primary badge-pill">{{ book.avg_rating|floatformat:1 }}</span>
<br>
{% endif %}
<hr>
{% if book.review_set.all %}
<h2 class="mt-3">Review Comments</h2>
{% for review in book.review_set.all %}
<div class="d-flex justify-content-center mb-2">
  <ul class="list-group list-group-flush" style="width: 95%;">
    <li class="border rounded list-group-item">
      <span class="text-info">Review Comment: </span>
      <span>{{ review.content }}</span>
      <br>
      <span class="text-info">Created on: </span>
      <span>{{ review.date_created }}</span>
      <br>
      <span class="text-info">Modified on: </span>
      <span>{{ review.date_edited }}</span>
      <br>
      <span class="text-info">Rating: </span>
      <span class="badge badge-secondary badge-pill">{{ review.rating }}</span>
      <br>
      <span class="text-info">Creator: </span>
      <span>{{ review.creator }}</span>
      <br>
    </li>
    <a style="text-decoration: none; padding-bottom: 5px;" href="/books/{{ book.id }}/reviews/{{ review.id }}/">Edit Review</a>
  </ul>
</div>
{% endfor %}
{% endif %}
<a class="btn btn-primary" href="/books/{{ book.id }}/reviews/new/">Add Review</a>
<a class="btn btn-primary" href="media/">Media</a>

{% endblock %}

templates/pages/book-list.html
{% extends '../layouts/base.html' %}

{% block body %}
<h1>Book Review application</h1>
<hr>
<ul>
  {% for book in books %}
  <li>
    <span class="text-info">Title: </span>
    <span>{{ book.title }}</span>
    <br>
    <span class="text-info">Publisher: </span>
    <span>{{ book.publisher }}</span>
    <br>
    <span class="text-info">Publication Date: </span>
    <span>{{ book.publication_date }}</span>
    <br>
    <span class="text-info">Rating: </span>
    <span>{{ book.book_rating }}</span>
    <br>
    <span class="text-info">Number of reviews: </span>
    <span class="badge badge-primary badge-pill">{{ book.number_of_reviews }}</span>
    <br>
    {% if not book.book_rating %}
    <span class="text-secondary">Provide a rating and write the first review for this book.</span>
    <br>
    {% endif %}
    <a href="/books/{{book.id}}/" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Reviews</a>
  </li>
<br>
  {% endfor %}
</ul>
{% endblock %}

templates/pages/book-search.html
{% extends '../layouts/base.html' %}

{% block body %}
<h2>Search for Books</h2>
<form>
  {{ search_form.as_p }}
  <button class="btn btn-primary">Search</button>
</form>

{% if books %}
<br>
<h3>Search Results for <em>{{ search_text }}</em></h3>
<ul style="list-style-type: none;">
  {% for book in books %}
  <li>
    <span class="text-info">Title: </span>
    <a style="text-decoration: none;" href="/books/{{ book.id }}/">{{ book.title }}</a>
    <br>
    {% for bookcontributor in book.bookcontributor_set.all %}
    <span class="text-info">Contributor: </span>
    <span>{{ bookcontributor.contributor.first_names }} {{ bookcontributor.contributor.last_names }}</span>
    <span class="text-info">Role: </span>
    <span>{{ bookcontributor.get_role_display }}</span>
    <br>
    {% endfor %}
  </li>
<br>
  {% endfor %}
</ul>
{% endif %}

{% if search_text and not books %}
<br>
<h3>No results found</h3>
{% endif %}

{% endblock %}

templates/pages/home.html
{% extends '../layouts/base.html' %}

{% block body %}
<h1 class="text-success">A+ Lập trình Web</h1>
{% endblock %}

templates/pages/instance-form.html
{% extends '../layouts/base.html' %}

{% block body %}
<h2>
  {% if instance %}
  Editing {{ model_type }} <em>{% if related_instance %} {{ related_instance.title}} {% else %} {{ instance }} {% endif %}</em>
  {% else %}
  New {{ model_type }} <em>{% if related_instance %} {{ related_instance.title }} {% endif %}</em>
  {% endif %}
</h2>
{% if related_instance %}
<p>For {{ related_model_type }} <em>{{ related_instance }}</em></p>
{% endif %}
<form method="post" {% if is_file_upload %} enctype="multipart/form-data" {% endif %}>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">
      {% if instance %}Save{% else %}Create{% endif %}
  </button>
</form>
{% endblock %}

templates/pages/profile.html
{% extends "layouts/base.html" %}

{% block body %}
<h2>Profile</h2>
<div>
  <p>
  Username: {{ user.username }} <br>
  Name: {{ user.first_name }}
  {{ user.last_name }}<br>
  Date Joined: {{ user.date_joined }} <br>
  Email: {{ user.email }}<br>
  Last Login: {{ user.last_login }}<br>
  </p>
</div>
{% endblock %}